apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "*" 
    http:
      paths:
      - backend:
          service:
            name: {{ include "node-app-frontend.fullname" . }}
            port:
              number: 3000
        path: /node.app
        pathType: Prefix